#!/bin/sh

handle() {
    event=$(echo "$1" | awk -F'>>' '{print $1}')
    data=$(echo "$1" | awk -F'>>' '{print $2}')
    case $event in
    windowtitle)
        echo "$(date +%s) $1"
        windowaddress="0x$data"
        echo "got $windowaddress"
        clients=$(hyprctl clients -j)
        class=$(echo "$clients" | jq -r ".[] | select(.address == \"$windowaddress\") | .class")
        [ "$class" != "firefox" ] && return
        title=$(echo "$clients" | jq -r ".[] | select(.address == \"$windowaddress\") | .title")
        echo "$title" | grep -q "^Extension:" || return
        floating=$(echo "$clients" | jq -r ".[] | select(.address == \"$windowaddress\") | .floating")
        echo "floating: $floating"
        fullscreen=$(echo "$clients" | jq -r ".[] | select(.address == \"$windowaddress\") | .fullscreen")
        echo "fullscreen: $fullscreen"
        # echo "dispatching togglefloating to address:$windowaddress"

        commands="dispatch focuswindow \"address:$windowaddress\""
        [ "$floating" = "true" ] || commands="$commands;dispatch togglefloating"
        [ "$fullscreen" = "false" ] || commands="$commands;dispatch fullscreen"
        commands="$commands;dispatch centerwindow"
        echo hyprctl --batch "$commands"
        hyprctl --batch "$commands"
        ;;
    # activewindow) return ;;
    # activewindowv2) return ;;
    *)
        echo "$(date +%s) $1"
        ;;
    esac
}

socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
